### ISSUE TITLE
What if length is negative.

### ISSUE THREAD

**Issue by gupta-ashwani** [sanaysarthak/oopc-project#1]
We have to check weather if the input is negative or not.

**Comment by sanaysarthak** [comment]
we will do all the exception handling later on.

**Comment by sanaysarthak** [comment]
firstly, we'll deal with adding the code into a single modular main file.

**Comment by sanaysarthak** [comment]
Changes are already done in the main branch.
Please raise a Pull Request first, so that it is easier to track changes.

![image](https://github.com/sanaysarthak/oopc-project/assets/66907138/bc2df93e-4a97-4092-b971-253f02459836)
